### ISSUE TITLE
0.7.0 does not build with --locked

### ISSUE THREAD

**Issue by wezm** [guoxbin/dtool#13]
Attempting to build the 0.7.0 release with `cargo build --release --locked` results in an error:

```
    Updating crates.io index
error: the lock file /home/wmoore/Projects/aur/dtool/src/dtool-0.7.0/Cargo.lock needs to be updated but --locked was passed to prevent this
```

I use `--locked` when building the AUR package to ensure that the build is reproducible. It appears that you have not committed the `Cargo.lock` file. [This is recommended](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) for binary packages.

**Comment by guoxbin** [comment]
Release with Cargo.lock:

https://github.com/guoxbin/dtool/releases/tag/v0.7.1

**Comment by wezm** [comment]
Excellent, thank you.
