### ISSUE TITLE
Tag releases for easier packaging

### ISSUE THREAD

**Issue by wezm** [guoxbin/dtool#4]
This looks like a really useful tool. I actually started building a very similar tool in Rust for doing hex conversion that other day but `dtool` does that and more! I'd like to create an [AUR](https://aur.archlinux.org/) package for it. It's best to build OS packages like this from downloadable tar archives so that the source code can be checked against a hash digest like SHA256. Would it be possible to create a git tag for releases? GitHub will then make tarballs available for each tagged release at: https://github.com/guoxbin/dtool/releases which I can use to build the package.

**Comment by guoxbin** [comment]
Thanks for your advice. I will make a release on github for every further version.
Now the v0.2.1 release is ready for you:
https://github.com/guoxbin/dtool/releases

**Comment by wezm** [comment]
Awesome, thanks. I've published the AUR package. https://aur.archlinux.org/packages/dtool/
